python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py

python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py

python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
python geneticAlgorithm.py
